### ISSUE TITLE
Apps keep unfreezing themselves without user interaction

### ISSUE THREAD

**Issue by leehyunkeun** [amitv87/SuperFreezZ#1]
I've noticed that several apps (e.g. `com.google.android.webview`) keep unfreezing themselves without any user interaction, i.e. the red lightning symbol keeps resetting to green after a certain time. The device is unrooted. How is this even possible?

**Comment by amitv87** [comment]
**com.google.android.webview** is a system package and can be used by any app for presenting webviews. Hence it can be started by any app. Practically almost all modern apps use webview to make web features/workflows accessible to the mobile apps.

FYI, this is not the original repo, it is just a fork.
You may report bugs/issues directly to the [original repo](https://gitlab.com/SuperFreezZ/SuperFreezZ).
